### ISSUE TITLE
sci-libs/cholmod-3.0.14-r2:0/0::stefantalpalaru  link is dead

### ISSUE THREAD

**Issue by Arniiiii** [stefantalpalaru/gentoo-overlay#172]
link is dead

https://github.com/stefantalpalaru/gentoo-overlay/blob/d0fa036e6e89baebd3db87836a416fc85532c059/sci-libs/cholmod/cholmod-3.0.14-r2.ebuild#L10C1-L10C48

```
cat ./var/tmp/portage/sci-libs/cholmod-3.0.14-r2/temp/build.log
>>> Downloading 'http://202.36.178.9/sage/cholmod-3.0.14.tar.bz2'
--2025-07-24 21:17:25--  http://202.36.178.9/sage/cholmod-3.0.14.tar.bz2
Connecting to 202.36.178.9:80... failed: Connection timed out.
Retrying.

--2025-07-24 21:18:26--  (try: 2)  http://202.36.178.9/sage/cholmod-3.0.14.tar.bz2
Connecting to 202.36.178.9:80... failed: Connection timed out.
Retrying.

--2025-07-24 21:19:28--  (try: 3)  http://202.36.178.9/sage/cholmod-3.0.14.tar.bz2
Connecting to 202.36.178.9:80... failed: Connection timed out.
Giving up.

!!! Couldn't download 'cholmod-3.0.14.tar.bz2'. Aborting.
```

**Comment by Arniiiii** [comment]
furthermore, it seems portage somehow took your ebuild instead of gentoo's for this.

also, it seems the package has a version 7.xxx on github.

**Comment by stefantalpalaru** [comment]
Fixed. Thank you for reporting it.

**Comment by iandoug** [comment]
Hi, i am still having an issue with this .. not sure where actual problem is.

>>> Failed to emerge sci-libs/ccolamd-2.9.6, Log file:

checking pkg-config is at least version 0.9.0... yes
checking for suitesparseconfig... no
configure: error: Package requirements (suitesparseconfig) were not met:

fractal ~ # eix suitesparseconfig
[I] sci-libs/suitesparseconfig
     Available versions:  5.4.0 [M]~7.0.0(0/7) (~)7.11.0(0/7)[1] {openmp static-libs ABI_MIPS="n32 n64 o32" ABI_S390="32 64" ABI_X86="32 64 x32"}
     Installed versions:  7.11.0(0/7)[1](09:23:45 28/07/2025)(openmp -static-libs ABI_MIPS="-n32 -n64 -o32" ABI_S390="-32 -64" ABI_X86="64 -32 -x32")
     Homepage:            https://people.engr.tamu.edu/davis/suitesparse.html
     Description:         Common configurations for all packages in suitesparse

[1] "stefantalpalaru" /var/db/repos/stefantalpalaru

Should I block your version of suitesparseconfig ?

Thanks, Ian

**Comment by iandoug** [comment]
Sorry I see different package but appears related to first post.

**Comment by stefantalpalaru** [comment]
> Should I block your version of suitesparseconfig ?

You should stop blocking my version of ccolamd, which is 3.3.5:

```text
# eix -se ccolamd
[I] sci-libs/ccolamd
     Available versions:  2.9.6 [M](~)3.0.3(0/3)^t (~)3.3.5(0/3)[1] {static-libs test ABI_MIPS="n32 n64 o32" ABI_S390="32 64" ABI_X86="32 64 x32"}
     Installed versions:  3.3.5(0/3)[1](11:50:20 PM 07/25/2025)(-static-libs ABI_MIPS="-n32 -n64 -o32" ABI_S390="-32 -64" ABI_X86="64 -32 -x32")
     Homepage:            https://people.engr.tamu.edu/davis/suitesparse.html
     Description:         Constrained Column approximate minimum degree ordering algorithm

[1] "stefantalpalaru" /src/77_DLD/CODE/00_github/gentoo-overlay
```

**Comment by iandoug** [comment]
Thanks, got it to work after also ~ sci-libs/amd and sci-libs/colamd

Cheers, Ian
