### ISSUE TITLE
vmware-modules-15.5.1-r1 with Linux 5.5.x

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#54]
Can the latest vmware-modules be built with Linux 5.5.x? I have locally modified your ebuild and changed `MY_KERNEL_VERSION` to 5.5, the modules are built, but I cannot start any VM. So, is this combination possible?

**Comment by stefantalpalaru** [comment]
Try the vmware-modules-15.5.1-r2 I just pushed.

**Comment by lourdas** [comment]
I did, but still the same error. After loading the modules, I get this error when trying to start a FreeBSD VM I have:

![Screenshot_20200225_215835](https://user-images.githubusercontent.com/397916/75282746-3af8cf80-581a-11ea-90fc-6d945f890676.png)

**Comment by lourdas** [comment]
Modules loaded:

    Module                  Size  Used by
    vmw_vsock_vmci_transport    24576  0
    vsock                  32768  1 vmw_vsock_vmci_transport
    vmw_vmci               57344  1 vmw_vsock_vmci_transport
    vmmon                  98304  0
    vboxnetadp             24576  0
    vboxnetflt             28672  0
    vboxdrv               389120  2 vboxnetadp,vboxnetflt

**Comment by lourdas** [comment]
In the mean time, VMware Workstation Pro [15.5.2](https://docs.vmware.com/en/VMware-Workstation-Pro/15.5/rn/VMware-Workstation-1552-Pro-Release-Notes.html) has been released. Could this work?

**Comment by stefantalpalaru** [comment]
Waiting for a "workstation-15.5.2" branch in https://github.com/mkubecek/vmware-host-modules

**Comment by stefantalpalaru** [comment]
vmware-workstation-15.5.2.15785246 now available. Please test it.

**Comment by lourdas** [comment]
Still the same error. Meanwhile, systemctl reports that vmware-vmblock.service and vmware-vmnet.service have failed. Apparently no vmblock module exists and vmware-vmnet.service fails partially.

I guess the last thing to try is to boot with a 5.4 kernel and recompile vmware-modules for 5.4.

Otherwise, I'll drop vmware workstation completely.

**Comment by Manfred-Knick** [comment]
Please c.f.     [https://bugs.gentoo.org/713068#c1 ]

@ Vasilis Lourdas < lourdas > :   NEEDINFO
. . . Please, elaborate details.

**Comment by lourdas** [comment]
Kernel 5.6.2. vmware-modules compiles cleanly. Still same error message. I will provide as much information as I can.

All systemd units except vmware-vmblock.service and vmware-vmnet.service start without any issue. journalctl for these provides:

    journalctl -u vmware-vmnet.service
    Απρ 05 09:48:57 helios systemd[1]: Starting VMware Virtual Ethernet...
    Απρ 05 09:48:57 helios systemd[1]: Started VMware Virtual Ethernet.
    Απρ 05 09:48:57 helios vmnetBridge[6482]: Bridge process created.
    Απρ 05 09:48:57 helios vmnetBridge[6482]: RTM_NEWLINK: name:eth0 index:2 flags:0x00011043
    Απρ 05 09:48:57 helios vmnetBridge[6482]: Adding interface eth0 index:2
    Απρ 05 09:48:57 helios vmnetBridge[6482]: Started bridge eth0 to virtual network 0.
    Απρ 05 09:48:57 helios vmnetBridge[6482]: RTM_NEWROUTE: index:2
    Απρ 05 09:48:58 helios vmware-networks[6480]: Failed to start NAT service on vmnet8
    Απρ 05 09:48:58 helios vmware-networks[6480]: Failed to start some/all services
    Απρ 05 09:48:58 helios vmware-networks[6480]: Started Bridge networking on vmnet0
    Απρ 05 09:48:58 helios vmware-networks[6480]: Enabled hostonly virtual adapter on vmnet1
    Απρ 05 09:48:58 helios vmware-networks[6480]: Started DHCP service on vmnet1
    Απρ 05 09:48:58 helios vmware-networks[6480]: Enabled hostonly virtual adapter on vmnet8
    Απρ 05 09:48:58 helios vmware-networks[6480]: Started DHCP service on vmnet8
    Απρ 05 09:48:58 helios systemd[1]: vmware-vmnet.service: Main process exited, code=exited, status=1/FAILURE
    Απρ 05 09:48:58 helios vmnetBridge[6482]: Stopped bridge eth0 to virtual network 0.
    Απρ 05 09:48:58 helios vmnetBridge[6482]: Bridge process exiting.
    Απρ 05 09:48:58 helios systemd[1]: vmware-vmnet.service: Failed with result 'exit-code'.

    journalctl -u vmware-vmblock.service
    Απρ 05 09:47:40 helios systemd[1]: Started VMware Blocking File System.
    Απρ 05 09:47:40 helios modprobe[6406]: modprobe: FATAL: Module vmblock not found in directory /lib/modules/5.6.2-gen>
    Απρ 05 09:47:40 helios systemd[1]: vmware-vmblock.service: Main process exited, code=exited, status=1/FAILURE
    Απρ 05 09:47:40 helios systemd[1]: vmware-vmblock.service: Failed with result 'exit-code'.
    Απρ 05 09:48:57 helios systemd[1]: Started VMware Blocking File System.
    Απρ 05 09:48:57 helios systemd[1]: vmware-vmblock.service: Main process exited, code=exited, status=1/FAILURE
    Απρ 05 09:48:57 helios modprobe[6477]: modprobe: FATAL: Module vmblock not found in directory /lib/modules/5.6.2-gen>
    Απρ 05 09:48:57 helios systemd[1]: vmware-vmblock.service: Failed with result 'exit-code'.

The log file of a FreeBSD vm that I try to start from workstation is:

    2020-04-05T09:55:48.966+03:00| vmui| I125: Log for VMware Workstation pid=6928 version=15.5.2 build=build-15785246 option=Release
    2020-04-05T09:55:48.966+03:00| vmui| I125: The process is 64-bit.
    2020-04-05T09:55:48.966+03:00| vmui| I125: Host codepage=UTF-8 encoding=UTF-8
    2020-04-05T09:55:48.966+03:00| vmui| I125: Host is Linux 5.6.2-gentoo Gentoo Base System release 2.6
    2020-04-05T09:55:48.963+03:00| host-6928| I125: Using GTK 3.14.15
    2020-04-05T09:55:48.965+03:00| host-6928| I125: UTIL: Change file descriptor limit from soft 1024,hard 524288 to soft 16384,hard 524288.
    2020-04-05T09:55:48.965+03:00| vmui| I125: VTHREAD 140685595338624 "vmui" tid 6928
    2020-04-05T09:55:48.965+03:00| vmui| I125: DictionaryLoad: Cannot open file "/opt/vmware/lib/vmware/settings": No such file or directory.
    2020-04-05T09:55:48.965+03:00| vmui| I125: [msg.dictionary.load.openFailed] Cannot open file "/opt/vmware/lib/vmware/settings": No such file or directory.
    2020-04-05T09:55:48.965+03:00| vmui| I125: PREF Optional preferences file not found at /opt/vmware/lib/vmware/settings. Using default values.
    2020-04-05T09:55:48.965+03:00| vmui| I125: DictionaryLoad: Cannot open file "/home/lourdas/.vmware/config": No such file or directory.
    2020-04-05T09:55:48.965+03:00| vmui| I125: [msg.dictionary.load.openFailed] Cannot open file "/home/lourdas/.vmware/config": No such file or directory.
    2020-04-05T09:55:48.965+03:00| vmui| I125: PREF Optional preferences file not found at /home/lourdas/.vmware/config. Using default values.
    2020-04-05T09:55:48.985+03:00| vmui| W115: PID: 6928, log output: /tmp/vmware-lourdas/vmware-ui-6928.log
    2020-04-05T09:55:48.985+03:00| vmui| I125: OBJLIB-LIB: Objlib initialized.
    2020-04-05T09:55:48.985+03:00| vmui| I125: lib/ssl: OpenSSL using FIPS_drbg for RAND
    2020-04-05T09:55:48.985+03:00| vmui| I125: lib/ssl: protocol list tls1.2
    2020-04-05T09:55:48.985+03:00| vmui| I125: lib/ssl: protocol list tls1.2 (openssl flags 0x17000000)
    2020-04-05T09:55:48.985+03:00| vmui| I125: lib/ssl: cipher list ECDHE+AESGCM:RSA+AESGCM:ECDHE+AES:RSA+AES
    2020-04-05T09:55:48.985+03:00| vmui| I125: lib/ssl: curves list prime256v1:secp384r1:secp521r1
    2020-04-05T09:55:48.989+03:00| vmui| I120: gVmomi: gvmomi_init: success.
    2020-04-05T09:55:48.998+03:00| vmui| I125: WQPoolAllocPoll : pollIx = 1, signalHandle = 14
    2020-04-05T09:55:48.998+03:00| vmui| I125: HALLoadLibrary: Could not dlopen libhal.so.1: libhal.so.1: cannot open shared object file: No such file or directory.
    2020-04-05T09:55:48.998+03:00| vmui| I125: HALLoadLibrary: Could not dlopen libhal.so.0: libhal.so.0: cannot open shared object file: No such file or directory.
    2020-04-05T09:55:49.013+03:00| vmui| I125: UUID: Unable to open /sys/firmware/efi/systab: Permission denied
    2020-04-05T09:55:49.013+03:00| vmui| I125: UUID: Unable to open /dev/mem: Permission denied
    2020-04-05T09:55:49.013+03:00| vmui| I125: UUID: Invalid gethostid routine. Value = 7F0100.
    2020-04-05T09:55:49.014+03:00| vmui| I125: vmxFilePath="/opt/vmware/lib/vmware/bin/vmware-vmx"
    2020-04-05T09:55:49.014+03:00| vmui| I125: vmxFilePathDebug="/opt/vmware/lib/vmware/bin/vmware-vmx-debug"
    2020-04-05T09:55:49.014+03:00| vmui| I125: vmxFilePathStats="/opt/vmware/lib/vmware/bin/vmware-vmx-stats"
    2020-04-05T09:55:49.014+03:00| vmui| I125: HostDeviceInfo_FindHostCDROMs: enumerating IDE CDROMs
    2020-04-05T09:55:49.014+03:00| vmui| I125: HostDeviceInfoFindHostIDECDROMs: /proc/ide could not be explored. Unable to enumerate host IDE cdroms.
    2020-04-05T09:55:49.014+03:00| vmui| I125: HostDeviceInfo_FindHostCDROMs: IDE CDROM enumerating completed
    2020-04-05T09:55:49.014+03:00| vmui| I125: HostDeviceInfo_FindHostCDROMs: enumerating SCSI CDROMs
    2020-04-05T09:55:49.065+03:00| vmui| I125: HostDeviceInfo_FindHostCDROMs: SCSI CDROM enumerating completed
    2020-04-05T09:55:49.206+03:00| vmui| I125: HostDeviceInfo_FindHostParallelPorts: /proc/sys/dev/parport could not be explored. Unable to enumerate host parallel ports.
    2020-04-05T09:55:49.239+03:00| vmui| I125: SMBIOS: can't open /dev/mem: Insufficient permission to access the file
    2020-04-05T09:55:49.239+03:00| vmui| I125: VmhsHostInfoPopulateSystem:  Could not get information from smbios to populate VMDB.
    2020-04-05T09:55:49.355+03:00| vthread-6994| I125: VTHREAD 140685362796288 "vthread-6994" tid 6994
    2020-04-05T09:55:49.356+03:00| vmui| I125: SOCKET creating new socket, connecting to /var/run/vmware/usbarbitrator-socket
    2020-04-05T09:55:49.356+03:00| vmui| I125: REM-USB: Protocol version min:15 current:17. hostId:52 3b a9 13 d1 fb d9 58-98 5d 54 db 19 07 9e 41
    2020-04-05T09:55:49.356+03:00| vmui| I125: REM-USB: Initializing 'Generic' backend
    2020-04-05T09:55:49.356+03:00| vmui| I125: REM-USB: Initializing 'Virtual CCID' backend
    2020-04-05T09:55:49.356+03:00| vmui| I125: USB-CCID:  dlopened default libpcsclite.so.1.
    2020-04-05T09:55:49.356+03:00| vmui| I125: USB-CCID: Could not establish context: SCARD_E_NO_SERVICE(0x8010001d).
    2020-04-05T09:55:49.356+03:00| vmui| W115: Could not initialize emulated USB smart card subsystem.
    2020-04-05T09:55:49.356+03:00| vmui| I125: REM-USB: Unable to initialize 'Virtual CCID' backend
    2020-04-05T09:55:49.358+03:00| vmui| I125: DictionaryLoad: Cannot open file "/home/lourdas/.vmware/preferences-private": No such file or directory.
    2020-04-05T09:55:49.358+03:00| vmui| I125: NewComponentMgr: 15.5.2(15785246)
    2020-04-05T09:55:49.358+03:00| vmui| I125: CDS: Initializing a CDS updater client 1.0 for product unknown, version 15.5.2.15785246 (workspace /home/lourdas/.cache/vmware/cds)
    2020-04-05T09:55:49.361+03:00| vmui| I125: CDS: No cached version for vmware-player
    2020-04-05T09:55:49.361+03:00| vmui| I125: RefreshComponentListWithDefaults: CDS_UNKNOWN_PRODUCT_ERROR for product player-windows
    2020-04-05T09:55:49.361+03:00| vmui| I125: CDS: No cached version for vmware-tools-darwin
    2020-04-05T09:55:49.361+03:00| vmui| I125: CDS: No cached version for vmware-tools-darwinPre15
    2020-04-05T09:55:49.361+03:00| vmui| I125: CDS: No cached version for vmware-tools-freebsd
    2020-04-05T09:55:49.361+03:00| vmui| I125: CDS: No cached version for vmware-tools-linux
    2020-04-05T09:55:49.361+03:00| vmui| I125: CDS: No cached version for vmware-tools-linuxPreGlibc25
    2020-04-05T09:55:49.361+03:00| vmui| I125: CDS: No cached version for vmware-tools-netware
    2020-04-05T09:55:49.361+03:00| vmui| I125: CDS: No cached version for vmware-tools-solaris
    2020-04-05T09:55:49.361+03:00| vmui| I125: CDS: No cached version for vmware-tools-winPre2k
    2020-04-05T09:55:49.361+03:00| vmui| I125: CDS: No cached version for vmware-tools-winPreVista
    2020-04-05T09:55:49.361+03:00| vmui| I125: CDS: No cached version for vmware-tools-windows
    2020-04-05T09:55:49.361+03:00| vmui| I125: CDS: No cached version for vmware-workstation
    2020-04-05T09:55:49.361+03:00| vmui| I125: RefreshComponentListWithDefaults: CDS_UNKNOWN_PRODUCT_ERROR for product ws-windows
    2020-04-05T09:55:49.361+03:00| vmui| I125: ToolsMgr: No installed version of ws, player, nor vmrc.
    2020-04-05T09:55:49.361+03:00| vmui| I125: NewComponentMgr: 15.5.2(15785246)
    2020-04-05T09:55:49.361+03:00| vmui| I125: CDS: Initializing a CDS updater client 1.0 for product ws-linux, version 15.5.2.15785246 (workspace /home/lourdas/.cache/vmware/cds)
    2020-04-05T09:55:49.364+03:00| vmui| I125: CDS: No cached version for vmware-player
    2020-04-05T09:55:49.364+03:00| vmui| I125: RefreshComponentListWithDefaults: CDS_UNKNOWN_PRODUCT_ERROR for product player-windows
    2020-04-05T09:55:49.364+03:00| vmui| I125: CDS: No cached version for vmware-tools-darwin
    2020-04-05T09:55:49.364+03:00| vmui| I125: CDS: No cached version for vmware-tools-darwinPre15
    2020-04-05T09:55:49.364+03:00| vmui| I125: CDS: No cached version for vmware-tools-freebsd
    2020-04-05T09:55:49.364+03:00| vmui| I125: CDS: No cached version for vmware-tools-linux
    2020-04-05T09:55:49.364+03:00| vmui| I125: CDS: No cached version for vmware-tools-linuxPreGlibc25
    2020-04-05T09:55:49.364+03:00| vmui| I125: CDS: No cached version for vmware-tools-netware
    2020-04-05T09:55:49.364+03:00| vmui| I125: CDS: No cached version for vmware-tools-solaris
    2020-04-05T09:55:49.364+03:00| vmui| I125: CDS: No cached version for vmware-tools-winPre2k
    2020-04-05T09:55:49.364+03:00| vmui| I125: CDS: No cached version for vmware-tools-winPreVista
    2020-04-05T09:55:49.364+03:00| vmui| I125: CDS: No cached version for vmware-tools-windows
    2020-04-05T09:55:49.364+03:00| vmui| I125: CDS: No cached version for vmware-workstation
    2020-04-05T09:55:49.364+03:00| vmui| W115: RefreshComponentListWithDefaults: Install database empty! Overriding install state of ws-linux
    2020-04-05T09:55:49.364+03:00| vmui| I125: RefreshComponentListWithDefaults: CDS_UNKNOWN_PRODUCT_ERROR for product ws-windows
    2020-04-05T09:55:49.380+03:00| vmui| I125: Phone Home: PhoneHome_CreateClient: Creating client for host https://vcsa.vmware.com/ph, collector workstation.15_0, instance 523ba913-d1fb-d958-985d-54db19079e41.
    2020-04-05T09:55:49.380+03:00| vmui| I125: Phone Home: PhoneHome_CreateClient: Will send phone home requests to "https://vcsa.vmware.com/ph/api/hyper/send?_c=workstation.15_0&_i=523ba913-d1fb-d958-985d-54db19079e41".
    2020-04-05T09:55:49.380+03:00| vmui| I125: Foundry Init: setting up global state (1 poll threads, 0 worker threads).
    2020-04-05T09:55:49.380+03:00| vmui| I125: Vix_InitializeGlobalState: vixLogLevel = 0
    2020-04-05T09:55:49.380+03:00| vmui| I125: Vix_InitializeGlobalState: vixApiTraceLevel = 0
    2020-04-05T09:55:49.380+03:00| vmui| I125: Vix_InitializeGlobalState: vixDebugPanicOnVixAssert = 0
    2020-04-05T09:55:49.380+03:00| vmui| I125: Vix_InitializeGlobalState: vixLogRefcountOnFinalRelease = 0
    2020-04-05T09:55:49.380+03:00| vmui| I125: Vix_InitializeGlobalState: asyncOpWarningThreshold = 1000000
    2020-04-05T09:55:49.380+03:00| vmui| I125: Vix_InitializeGlobalState: enableSyncOpSelection = FALSE
    2020-04-05T09:55:49.380+03:00| vmui| I125: Vix_InitializeGlobalState: enableExternalThreadInterface = TRUE
    2020-04-05T09:55:49.380+03:00| vmui| I125: Vix_InitializeGlobalState: enableVigor = FALSE
    2020-04-05T09:55:49.380+03:00| vmui| I125: VixHost_ConnectEx: version -1, hostType 3, hostName (null), hostPort 0, options 8707
    2020-04-05T09:55:49.406+03:00| vmui| I125: OnHostTopologyChanged, found host monitor 0: 1920x1080 @ 0,0 (scale: 1)
    2020-04-05T09:55:49.406+03:00| vmui| I125: OnHostTopologyChanged, I'm now on monitor 0: 1920x1080 @ 0,0
    2020-04-05T09:55:49.406+03:00| vmui| I125: OnWindowManagerChanged: found Window Manager: KWin, with fullscreen capability: 2
    2020-04-05T09:55:49.504+03:00| vmui| I125: Printing loaded objects
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x55C4A4F25000-0x55C4A4FDA6C4): vmware
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FFE941A9000-0x7FFE941A9B5C): linux-vdso.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3EB30A000-0x7FF3EB30BEA0): /lib64/librt.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3EB304000-0x7FF3EB304D90): /lib64/libdl.so.2
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3EB0ED000-0x7FF3EB10220C): /opt/vmware/lib/vmware/lib/libgcc_s.so.1/libgcc_s.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3EB0C8000-0x7FF3EB0CDD38): /lib64/libpthread.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3EAEF9000-0x7FF3EAF1A400): /lib64/libc.so.6
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3EB36D000-0x7FF3EB36DEA8): /lib64/ld-linux-x86-64.so.2
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3EAEEC000-0x7FF3EAEED650): /lib64/libnss_db.so.2
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3EAEDE000-0x7FF3EAEE00B0): /lib64/libnss_files.so.2
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3EA965000-0x7FF3EAC5C5BE): /opt/vmware/lib/vmware/lib/libvmware.so/libvmware.so
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3EA637000-0x7FF3EA760524): /opt/vmware/lib/vmware/lib/libglib-2.0.so.0/libglib-2.0.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3EA3E0000-0x7FF3EA43459C): /opt/vmware/lib/vmware/lib/libgobject-2.0.so.0/libgobject-2.0.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3EA170000-0x7FF3EA1DB086): /opt/vmware/lib/vmware/lib/libglibmm-2.4.so.1/libglibmm-2.4.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E9F6A000-0x7FF3E9F6E36D): /opt/vmware/lib/vmware/lib/libsigc-2.0.so.0/libsigc-2.0.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E9D20000-0x7FF3E9D6329C): /opt/vmware/lib/vmware/lib/libatkmm-1.6.so.1/libatkmm-1.6.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E9AFC000-0x7FF3E9B1D5F9): /opt/vmware/lib/vmware/lib/libcairomm-1.0.so.1/libcairomm-1.0.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E8DD0000-0x7FF3E98D648C): /opt/vmware/lib/vmware/lib/libgtk-3.so.0/libgtk-3.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E8B2C000-0x7FF3E8BC9CD4): /opt/vmware/lib/vmware/lib/libgdk-3.so.0/libgdk-3.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E88EA000-0x7FF3E8926EBC): /opt/vmware/lib/vmware/lib/libgdkmm-3.0.so.1/libgdkmm-3.0.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E822B000-0x7FF3E8631094): /opt/vmware/lib/vmware/lib/libgtkmm-3.0.so.1/libgtkmm-3.0.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E8000000-0x7FF3E80278A6): /opt/vmware/lib/vmware/lib/libpangomm-1.4.so.1/libpangomm-1.4.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E7DCF000-0x7FF3E7EF9EBC): /opt/vmware/lib/vmware/lib/libX11.so.6/libX11.so.6
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E7CCD000-0x7FF3E7CCE784): /opt/vmware/lib/vmware/lib/libXinerama.so.1/libXinerama.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E7AC3000-0x7FF3E7ACAC4C): /opt/vmware/lib/vmware/lib/libbasichttp.so/libbasichttp.so
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E7156000-0x7FF3E788EC0C): /opt/vmware/lib/vmware/lib/libgvmomi.so/libgvmomi.so
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E65F4000-0x7FF3E6E82994): /opt/vmware/lib/vmware/lib/libvmwarebase.so/libvmwarebase.so
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E4851000-0x7FF3E610E52F): /opt/vmware/lib/vmware/lib/libvmwareui.so/libvmwareui.so
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E44D1000-0x7FF3E4640CDA): /opt/vmware/lib/vmware/lib/libstdc++.so.6/libstdc++.so.6
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E4386000-0x7FF3E4392008): /lib64/libm.so.6
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E410C000-0x7FF3E4183F2C): /opt/vmware/lib/vmware/lib/libpcre.so.1/libpcre.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E3F02000-0x7FF3E3F09D1C): /opt/vmware/lib/vmware/lib/libffi.so.6/libffi.so.6
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E3CFE000-0x7FF3E3D006A4): /opt/vmware/lib/vmware/lib/libgmodule-2.0.so.0/libgmodule-2.0.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E3AD8000-0x7FF3E3AFA60C): /opt/vmware/lib/vmware/lib/libatk-1.0.so.0/libatk-1.0.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E3819000-0x7FF3E38D025C): /opt/vmware/lib/vmware/lib/libfreetype.so.6/libfreetype.so.6
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E35F2000-0x7FF3E3616B64): /opt/vmware/lib/vmware/lib/libpng12.so.0/libpng12.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E33DA000-0x7FF3E33F0264): /opt/vmware/lib/vmware/lib/libz.so.1/libz.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E32D1000-0x7FF3E32D8FC4): /opt/vmware/lib/vmware/lib/libXrender.so.1/libXrender.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E2F9A000-0x7FF3E30CB57C): /opt/vmware/lib/vmware/lib/libcairo.so.2/libcairo.so.2
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E2E89000-0x7FF3E2E98874): /opt/vmware/lib/vmware/lib/libXext.so.6/libXext.so.6
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E2C7B000-0x7FF3E2C874CC): /opt/vmware/lib/vmware/lib/libpangocairo-1.0.so.0/libpangocairo-1.0.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E2B6D000-0x7FF3E2B7A59C): /opt/vmware/lib/vmware/lib/libXi.so.6/libXi.so.6
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E2A68000-0x7FF3E2A6C414): /opt/vmware/lib/vmware/lib/libXfixes.so.3/libXfixes.so.3
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E285F000-0x7FF3E286517C): /opt/vmware/lib/vmware/lib/libcairo-gobject.so.2/libcairo-gobject.so.2
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E24DB000-0x7FF3E2656494): /opt/vmware/lib/vmware/lib/libgdk_pixbuf-2.0.so.0/libgdk_pixbuf-2.0.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E2285000-0x7FF3E22D5D9C): /opt/vmware/lib/vmware/lib/libatk-bridge-2.0.so.0/libatk-bridge-2.0.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E206D000-0x7FF3E2082C74): /opt/vmware/lib/vmware/lib/libpangoft2-1.0.so.0/libpangoft2-1.0.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E1E17000-0x7FF3E1E6862C): /opt/vmware/lib/vmware/lib/libpango-1.0.so.0/libpango-1.0.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E1BC4000-0x7FF3E1C142B4): /opt/vmware/lib/vmware/lib/libfontconfig.so.1/libfontconfig.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E181B000-0x7FF3E19B8BA4): /opt/vmware/lib/vmware/lib/libgio-2.0.so.0/libgio-2.0.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E1714000-0x7FF3E171A8F4): /opt/vmware/lib/vmware/lib/libXrandr.so.2/libXrandr.so.2
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E160A000-0x7FF3E1612B34): /opt/vmware/lib/vmware/lib/libXcursor.so.1/libXcursor.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E1508000-0x7FF3E1509A34): /opt/vmware/lib/vmware/lib/libXcomposite.so.1/libXcomposite.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E1406000-0x7FF3E14077F4): /opt/vmware/lib/vmware/lib/libXdamage.so.1/libXdamage.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E1086000-0x7FF3E11EBAD4): /opt/vmware/lib/vmware/lib/libgiomm-2.4.so.1/libgiomm-2.4.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E0F68000-0x7FF3E0F84964): /opt/vmware/lib/vmware/lib/libxcb.so.1/libxcb.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E0CF5000-0x7FF3E0D649E4): /opt/vmware/lib/vmware/lib/libcurl.so.4/libcurl.so.4
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E092F000-0x7FF3E0AE9B1C): /opt/vmware/lib/vmware/lib/libxml2.so.2/libxml2.so.2
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E06F9000-0x7FF3E072B6E4): /opt/vmware/lib/vmware/lib/libcds.so/libcds.so
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E047C000-0x7FF3E04EDB14): /opt/vmware/lib/vmware/lib/libgcr-ui-3.so.1/libgcr-ui-3.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E01E0000-0x7FF3E026E194): /opt/vmware/lib/vmware/lib/libgcr-base-3.so.1/libgcr-base-3.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3E00DD000-0x7FF3E00DEE1C): /opt/vmware/lib/vmware/lib/libXau.so.6/libXau.so.6
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DFE0C000-0x7FF3DFED3B6C): /opt/vmware/lib/vmware/lib/libpixman-1.so.0/libpixman-1.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DFBCB000-0x7FF3DFC0A444): /opt/vmware/lib/vmware/lib/libdbus-1.so.3/libdbus-1.so.3
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DF96A000-0x7FF3DF9C8504): /opt/vmware/lib/vmware/lib/libharfbuzz.so.0/libharfbuzz.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DF961000-0x7FF3DF962498): /lib64/libuuid.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DF948000-0x7FF3DF94B4D0): /lib64/libresolv.so.2
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DF843000-0x7FF3DF8472DC): /opt/vmware/lib/vmware/lib/libXdmcp.so.6/libXdmcp.so.6
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DF384000-0x7FF3DF6118AC): /opt/vmware/lib/vmware/lib/libcrypto.so.1.0.2/libcrypto.so.1.0.2
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DF111000-0x7FF3DF1787D4): /opt/vmware/lib/vmware/lib/libssl.so.1.0.2/libssl.so.1.0.2
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DEEDD000-0x7FF3DEF0DFDC): /opt/vmware/lib/vmware/lib/libgck-1.so.0/libgck-1.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DEB8F000-0x7FF3DECD503C): /opt/vmware/lib/vmware/lib/libgcrypt.so.20/libgcrypt.so.20
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DE910000-0x7FF3DE98272C): /opt/vmware/lib/vmware/lib/libp11-kit.so.0/libp11-kit.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DE903000-0x7FF3DE9036A8): /usr/lib64/gconv/UTF-16.so
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DD7B5000-0x7FF3DD7E13B8): /usr/lib64/libasound.so.2
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DD760000-0x7FF3DD76C1E8): /usr/lib64/libpulse.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DD6DB000-0x7FF3DD6EEEF0): /usr/lib64/pulseaudio/libpulsecommon-13.0.so
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3EB34F000-0x7FF3EB34F408): /usr/lib64/libX11-xcb.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DD5C0000-0x7FF3DD5D5DB4): /opt/vmware/lib/vmware/lib/libICE.so.6/libICE.so.6
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DD4B9000-0x7FF3DD4BFB04): /opt/vmware/lib/vmware/lib/libSM.so.6/libSM.so.6
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DD3B4000-0x7FF3DD3B87FC): /opt/vmware/lib/vmware/lib/libXtst.so.6/libXtst.so.6
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DD2FA000-0x7FF3DD30AB48): /lib64/libsystemd.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3EB343000-0x7FF3EB345810): /lib64/libwrap.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DD27F000-0x7FF3DD2850D0): /usr/lib64/libsndfile.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3EB33D000-0x7FF3EB33DF88): /usr/lib64/libasyncns.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3EB314000-0x7FF3EB316CB8): /lib64/liblzma.so.5
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DD25D000-0x7FF3DD25F970): /usr/lib64/liblz4.so.1
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DD255000-0x7FF3DD256860): /lib64/libcap.so.2
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DD216000-0x7FF3DD21EA00): /usr/lib64/libFLAC.so.8
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DD20B000-0x7FF3DD20C718): /usr/lib64/libogg.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DD1DD000-0x7FF3DD1E0158): /usr/lib64/libvorbis.so.0
    2020-04-05T09:55:49.504+03:00| vmui| I125: [0x7FF3DD132000-0x7FF3DD145930): /usr/lib64/libvorbisenc.so.2
    2020-04-05T09:55:49.504+03:00| vmui| I125: End printing loaded objects
    2020-04-05T09:55:49.510+03:00| vmui| I125: VMMgr::OpenVM (cfgPath=/media/ext2/vmachines/FreeBSD12/FreeBSD 12 64-bit.vmx)
    2020-04-05T09:55:49.511+03:00| vmui| I125: VMMgr::OpenVM (cfgPath=/media/ext2/vmachines/Windows 10 x64/Windows 10 x64.vmx)
    2020-04-05T09:55:49.512+03:00| vmui| I125: VMMgr::OpenVM (cfgPath=/media/ext/vmachines/Windows 7 x64/Windows 7 x64.vmx)
    2020-04-05T09:55:49.514+03:00| host-7034| I125: /media/ext2/vmachines/FreeBSD12/FreeBSD 12 64-bit.vmx: Reloading config state.
    2020-04-05T09:55:49.515+03:00| vmui| I125: BasicHttpOnSent: xmlReadMemory (NULL == xmlDoc) errorCode 0 responseCode 404 message <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    2020-04-05T09:55:49.515+03:00| vmui| I125+ <html><head>
    2020-04-05T09:55:49.515+03:00| vmui| I125+ <title>404 Not Found</title>
    2020-04-05T09:55:49.515+03:00| vmui| I125+ </head><body>
    2020-04-05T09:55:49.515+03:00| vmui| I125+ <h1>Not Found</h1>
    2020-04-05T09:55:49.515+03:00| vmui| I125+ <p>The requested URL was not found on this server.</p>
    2020-04-05T09:55:49.515+03:00| vmui| I125+ <hr>
    2020-04-05T09:55:49.515+03:00| vmui| I125+ <address>Apache Server at 127.0.0.1 Port 443</address>
    2020-04-05T09:55:49.515+03:00| vmui| I125+ </body></html>
    2020-04-05T09:55:49.515+03:00| vmui| I125+ 
    2020-04-05T09:55:49.517+03:00| host-7034| I125: VMHS: Transitioned vmx/execState/val to poweredOff
    2020-04-05T09:55:49.520+03:00| host-7033| I125: /media/ext/vmachines/Windows 7 x64/Windows 7 x64.vmx: Reloading config state.
    2020-04-05T09:55:49.524+03:00| host-7033| I125: VMHS: Transitioned vmx/execState/val to poweredOff
    2020-04-05T09:55:49.527+03:00| host-7035| I125: /media/ext2/vmachines/Windows 10 x64/Windows 10 x64.vmx: Reloading config state.
    2020-04-05T09:55:49.530+03:00| host-7035| I125: VMHS: Transitioned vmx/execState/val to poweredOff
    2020-04-05T09:55:49.565+03:00| vigorCnx| I125: VTHREAD 140685270824704 "vigorCnx" tid 7042
    2020-04-05T09:55:49.566+03:00| vmui| I125: SnapshotTree: Populating (/media/ext2/vmachines/Windows 10 x64/Windows 10 x64.vmx)
    2020-04-05T09:55:49.566+03:00| vmui| I125: SnapshotTree: Emitting refresh (/media/ext2/vmachines/Windows 10 x64/Windows 10 x64.vmx)
    2020-04-05T09:55:49.568+03:00| vigorCnx| I125: VTHREAD 140685262432000 "vigorCnx" tid 7043
    2020-04-05T09:55:49.569+03:00| vmui| I125: SnapshotTree: Populating (/media/ext/vmachines/Windows 7 x64/Windows 7 x64.vmx)
    2020-04-05T09:55:49.569+03:00| vmui| I125: SnapshotTree: Emitting refresh (/media/ext/vmachines/Windows 7 x64/Windows 7 x64.vmx)
    2020-04-05T09:55:49.570+03:00| vigorCnx| I125: VTHREAD 140685254039296 "vigorCnx" tid 7044
    2020-04-05T09:55:49.571+03:00| vmui| I125: SnapshotTree: Populating (/media/ext2/vmachines/FreeBSD12/FreeBSD 12 64-bit.vmx)
    2020-04-05T09:55:49.571+03:00| vmui| I125: SnapshotTree: Emitting refresh (/media/ext2/vmachines/FreeBSD12/FreeBSD 12 64-bit.vmx)
    2020-04-05T09:55:49.580+03:00| vigorCnx| I125: VigorOfflineGetToolsVersion: updated tools version to 7fffffff
    2020-04-05T09:55:49.580+03:00| vigorCnx| I125: VigorOfflineGetToolsVersion: updated tools version to 286a
    2020-04-05T09:55:49.581+03:00| vigorCnx| I125: VigorOfflineGetToolsVersion: updated tools version to 2c01
    2020-04-05T09:55:49.608+03:00| vmui| I125: SnapshotTree: Emitting refresh (/media/ext2/vmachines/FreeBSD12/FreeBSD 12 64-bit.vmx)
    2020-04-05T09:55:49.608+03:00| vmui| I125: SnapshotTree: Populating (/media/ext2/vmachines/FreeBSD12/FreeBSD 12 64-bit.vmx)
    2020-04-05T09:55:49.610+03:00| vmui| I125: SnapshotTree: Emitting refresh (/media/ext/vmachines/Windows 7 x64/Windows 7 x64.vmx)
    2020-04-05T09:55:49.610+03:00| vmui| I125: SnapshotTree: Populating (/media/ext/vmachines/Windows 7 x64/Windows 7 x64.vmx)
    2020-04-05T09:55:49.622+03:00| vmui| I125: OnVMStateChanged: alive = 0
    2020-04-05T09:55:49.623+03:00| vmui| I125: VMMKS: to observe MKS device.
    2020-04-05T09:55:49.624+03:00| vmui| I125: VMMKS::OnMKSDeviceInfoChanged: reset pipe name now in offline.
    2020-04-05T09:55:49.624+03:00| vmui| I125: VMMKS::OnInitVMDeviceObserverDone: done.
    2020-04-05T09:55:49.624+03:00| vmui| I125: VMMgr: Finished opening VM at /vm/#c46f1245e2b1db75/ from /media/ext2/vmachines/FreeBSD12/FreeBSD 12 64-bit.vmx
    2020-04-05T09:55:49.641+03:00| vmui| I125: HandleGuestTopologyChange: main UI rect: 1920x1080 @ 0,0
    2020-04-05T09:55:49.641+03:00| vmui| I125: HandleGuestTopologyChange: Found 0 present screens
    2020-04-05T09:55:49.641+03:00| vmui| I125: HandleGuestTopologyChange: Windows for extra guest monitors will not be shown
    2020-04-05T09:55:49.654+03:00| vmui| I125: SnapshotTree: Emitting refresh (/media/ext2/vmachines/Windows 10 x64/Windows 10 x64.vmx)
    2020-04-05T09:55:49.654+03:00| vmui| I125: SnapshotTree: Populating (/media/ext2/vmachines/Windows 10 x64/Windows 10 x64.vmx)
    2020-04-05T09:55:49.654+03:00| vmui| I125: OnVMStateChanged: alive = 0
    2020-04-05T09:55:49.654+03:00| vmui| I125: VMMKS: to observe MKS device.
    2020-04-05T09:55:49.661+03:00| vmui| I125: VMMKS::OnMKSDeviceInfoChanged: reset pipe name now in offline.
    2020-04-05T09:55:49.661+03:00| vmui| I125: VMMKS::OnInitVMDeviceObserverDone: done.
    2020-04-05T09:55:49.661+03:00| vmui| I125: VMMgr: Finished opening VM at /vm/#00004fa9cabd4984/ from /media/ext/vmachines/Windows 7 x64/Windows 7 x64.vmx
    2020-04-05T09:55:49.730+03:00| vmui| I125: OnVMStateChanged: alive = 0
    2020-04-05T09:55:49.730+03:00| vmui| I125: VMMKS: to observe MKS device.
    2020-04-05T09:55:49.731+03:00| vmui| I125: VMMKS::OnMKSDeviceInfoChanged: reset pipe name now in offline.
    2020-04-05T09:55:49.731+03:00| vmui| I125: VMMKS::OnInitVMDeviceObserverDone: done.
    2020-04-05T09:55:49.731+03:00| vmui| I125: VMMgr: Finished opening VM at /vm/#742e4f0e4ec3a2cf/ from /media/ext2/vmachines/Windows 10 x64/Windows 10 x64.vmx
    2020-04-05T09:55:50.107+03:00| vmui| I125: VMHSGetDataFileKey: Could not get the dataFileKey from VMDB
    2020-04-05T09:55:50.114+03:00| vmui| I125: VMHSGetDataFileKey: Could not get the dataFileKey from VMDB
    2020-04-05T09:55:50.160+03:00| vmui| I125: VMHSGetDataFileKey: Could not get the dataFileKey from VMDB
    2020-04-05T09:55:54.610+03:00| vmui| I125: Found vmx as /opt/vmware/lib/vmware/bin/vmware-vmx
    2020-04-05T09:55:54.610+03:00| vmui| I125: Starting vmx as /opt/vmware/lib/vmware/bin/vmware-vmx
    2020-04-05T09:55:54.610+03:00| vmui| I125: VigorExecVMXExCommon: VM /media/ext2/vmachines/FreeBSD12/FreeBSD 12 64-bit.vmx in directory /media/ext2/vmachines/FreeBSD12
    2020-04-05T09:55:54.610+03:00| vmui| I125: VigorExecVMXExCommon: Exec()'ing /opt/vmware/lib/vmware/bin/vmware-vmx /media/ext2/vmachines/FreeBSD12/FreeBSD 12 64-bit.vmx.
    2020-04-05T09:55:55.631+03:00| vmui| I125: VmdbAddConnection: cnxPath=/db/connection/#2a/, cnxIx=1
    2020-04-05T09:55:55.632+03:00| vmui| I125: VmdbPipeStreamsOvlError: write failed, draining reads
    2020-04-05T09:55:55.632+03:00| vmui| I125: VmdbPipeStreamsOvlError Couldn't read: OVL_STATUS_EOF (remote disconnect)
    2020-04-05T09:55:55.632+03:00| vmui| I125: VmdbPipeStreamsOvlError Couldn't initiate write: (32) Broken pipe.
    2020-04-05T09:55:55.632+03:00| vmui| I125: VmdbCnxDisconnect: Disconnect: closed pipe for sub cnx '/db/connection/#2a/' (-31)
    2020-04-05T09:55:55.632+03:00| vmui| I125: /media/ext2/vmachines/FreeBSD12/FreeBSD 12 64-bit.vmx: VMX did not report err via stderr
    2020-04-05T09:55:55.632+03:00| vmui| I125: VmdbDbRemoveCnx: Removing Cnx from Db for '/db/connection/#2a/'
    2020-04-05T09:55:55.632+03:00| vmui| I125: VersionAsyncSendRecv: VmdbCnxAsyncSend() failed, cnx = /db/connection/#2a/type/sub/, ret = Pipe: Write failed
    2020-04-05T09:55:55.632+03:00| vmui| I125: Vmdb_AddConnectionAsync_Secure: registered VERSION completion callback, cnx = /db/connection/#2a/
    2020-04-05T09:55:55.655+03:00| vmui| I125: OnVMStateChanged: alive = 1
    2020-04-05T09:55:55.656+03:00| vmui| I125: /media/ext2/vmachines/FreeBSD12/FreeBSD 12 64-bit.vmx: Reloading config state.
    2020-04-05T09:55:55.660+03:00| vmui| I125: VMHS: Transitioned vmx/execState/val to poweredOff
    2020-04-05T09:55:55.661+03:00| vigorCnx| I125: VigorOfflineGetToolsVersion: updated tools version to 7fffffff
    2020-04-05T09:55:55.662+03:00| vmui| I125: /media/ext2/vmachines/FreeBSD12/FreeBSD 12 64-bit.vmx: VMHSStartVmxVigorCb: vmPath=/vm/#c46f1245e2b1db75/ status=error
    2020-04-05T09:55:55.662+03:00| vmui| I125: /media/ext2/vmachines/FreeBSD12/FreeBSD 12 64-bit.vmx: VMHSStartVmxVigorCb: error vmdb=-45 msg=Failed to power on '/media/ext2/vmachines/FreeBSD12/FreeBSD 12 64-bit.vmx'.
    2020-04-05T09:55:55.662+03:00| vmui| I125+ 
    2020-04-05T09:55:55.662+03:00| vmui| I125: vm power operation abort, error = Failed to power on '/media/ext2/vmachines/FreeBSD12/FreeBSD 12 64-bit.vmx'.
    2020-04-05T09:55:55.662+03:00| vmui| I125+  .
    2020-04-05T09:55:55.689+03:00| vmui| I125: OnVMStateChanged: alive = 0
    2020-04-05T09:55:55.689+03:00| vmui| I125: VMMKS::OnMKSDeviceInfoChanged: reset pipe name now in offline.
    2020-04-05T09:55:55.714+03:00| vmui| I125: SnapshotTree: Populating (/media/ext2/vmachines/FreeBSD12/FreeBSD 12 64-bit.vmx)
    2020-04-05T09:55:55.714+03:00| vmui| I125: SnapshotTree: Emitting refresh (/media/ext2/vmachines/FreeBSD12/FreeBSD 12 64-bit.vmx)
    2020-04-05T09:55:55.727+03:00| vmui| I125: Vix: [foundryVMPowerOps.c:988]: FoundryVMPowerStateChangeCallback: /media/ext2/vmachines/FreeBSD12/FreeBSD 12 64-bit.vmx, vmx/execState/val = poweredOff.
    2020-04-05T09:55:56.229+03:00| vmui| I125: VMHSGetDataFileKey: Could not get the dataFileKey from VMDB
    2020-04-05T09:55:58.501+03:00| vmui| I125: VMMgr::CloseVM: closing VM at /vm/#742e4f0e4ec3a2cf/
    2020-04-05T09:55:58.547+03:00| vmui| I125: VMMgr::OnVMDestroyed: cleaning up after destroyed VM at /vm/#742e4f0e4ec3a2cf/
    2020-04-05T09:55:58.547+03:00| vmui| I125: VMMgr::CloseVM: closing VM at /vm/#00004fa9cabd4984/
    2020-04-05T09:55:58.548+03:00| vmui| I125: MKSWindowTrans: The current transaction 55C4A764E000 has not been submitted.
    2020-04-05T09:55:58.548+03:00| vmui| I125: MKSControlClient: Disconnect is called.
    2020-04-05T09:55:58.567+03:00| vmui| I125: VMMgr::OnVMDestroyed: cleaning up after destroyed VM at /vm/#00004fa9cabd4984/
    2020-04-05T09:55:58.567+03:00| vmui| I125: VMMgr::CloseVM: closing VM at /vm/#c46f1245e2b1db75/
    2020-04-05T09:55:58.567+03:00| vmui| I125: MKSWindowTrans: The current transaction 55C4A75F4B90 has not been submitted.
    2020-04-05T09:55:58.567+03:00| vmui| I125: MKSControlClient: Disconnect is called.
    2020-04-05T09:55:58.603+03:00| vmui| I125: VMMgr::OnVMDestroyed: cleaning up after destroyed VM at /vm/#c46f1245e2b1db75/
    2020-04-05T09:55:58.603+03:00| vmui| I125: MKSWindowTrans: The current transaction 55C4A6FC2840 has not been submitted.
    2020-04-05T09:55:58.603+03:00| vmui| I125: MKSControlClient: Disconnect is called.
    2020-04-05T09:55:58.618+03:00| vmui| I125: WORKER: asyncOps=0 maxActiveOps=0 maxPending=0 maxCompleted=0

Kernel modules loaded:

    lsmod
    Module                  Size  Used by
    vmw_vsock_vmci_transport    24576  0
    vsock                  32768  1 vmw_vsock_vmci_transport
    vmmon                  98304  0
    vmw_vmci               57344  1 vmw_vsock_vmci_transport

**Comment by lourdas** [comment]
Still the same error with kernel 5.6.5. Any help? I attached what logs I could find in my previous comment. Is there anything wrong with my kernel config?

**Comment by stefantalpalaru** [comment]
The "vmnet" kernel module is not loaded and you're using Systemd init scripts, instead of the OpenRC ones I'm using. I can't spot other differences.

Here are some hints for debugging VMware networking issues: https://evanhoffman.com/2011/02/23/vmware-workstation-7-virtual-ethernet-fails-to-start-after-changing-vmnet8-subnet/

Could you have port forwarding enabled? This might lead to a port number collision: https://superuser.com/questions/643567/networking-is-broken-in-my-vmware-10-0-vms-after-upgrading-to-windows-8-1

Worth redoing your VMware networking setup, starting with something simple.

**Comment by lourdas** [comment]
My network config is like this:

![Screenshot_20200419_212442](https://user-images.githubusercontent.com/397916/79696243-44377300-8284-11ea-8c42-01fec90a6972.png)

**Comment by stefantalpalaru** [comment]
Here's mine:

![img](https://i.imgur.com/GPXUwRf.png)

I don't see anything suspicious.

**Comment by lourdas** [comment]
Could you attach your kernel config to compare it with mine?

**Comment by Manfred-Knick** [comment]
On 19.04.20 20:45, Vasilis Lourdas wrote:
> Could you attach your kernel config to compare it with mine?
> 

Missing the first OP, I don't know about the original problem.

For the moment, I can confirm that the following ensemble WORKSFORME:

# uname -a

Linux xxx.yyy.de 5.6.5-gentoo #1 SMP Sat Apr 18 18:04:51 CEST 2020
       x86_64 Intel(R) Xeon(R) CPU E3-1276 v3 @ 3.60GHz GenuineIntel GNU/Linux


# equery list vmware* nvidia-drivers openrc

[I-O] [  ] app-emulation/vmware-modules-15.5.2:0
[I-O] [  ] app-emulation/vmware-workstation-15.5.2.15785246:0

[IP-] [  ] x11-drivers/nvidia-drivers-440.82:0/440

[IP-] [  ] sys-apps/openrc-0.42.1:0


HTH
Kind regards
Manfred

**Comment by stefantalpalaru** [comment]
> Could you attach your kernel config to compare it with mine?

**Comment by lourdas** [comment]
Still same error with 5.7.1. I have given up on this one. Unmerged vmware-modules and workstation. Will use Virtualbox instead. Feel free to close this issue.

**Comment by lourdas** [comment]
Just a comment. Just yesterday, I found the issue of the original problem. My kernel config was missing the CONFIG_X86_IOPL_IOPERM option enabled. After I enabled it, my VMs start up fine.

**Comment by stefantalpalaru** [comment]
Not a new issue, apparently: https://communities.vmware.com/t5/VMware-Workstation-Player/VMware-Player-15-5-2-fails-to-start-newly-created-vm-aborts-in/td-p/530670

I will add this to the kernel config check in vmware-modules.

**Comment by lourdas** [comment]
Not a new issue yes, I just wish I had found it much earlier. Please add it to the kernel config check.
